sudo: required
services:
    - docker

before_install:
    - docker build -t mhnm02/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true mhnm02/react-test npm test

after_success:
    # create prod builds
    - docker build -t mhnm02/multi-client ./client
    - docker build -t mhnm02/multi-nginx ./nginx
    - docker build -t mhnm02/multi-server ./server
    - docker build -t mhnm02/multi-worker ./worker
    # Log into docker CLI; first create env variables DOCKER_ID, DOCKER_PASSWORD in travis UI
    - echo "$DOCKER_PASSWORD" | docker -u "$DOCKER_ID" --password-stdin
    # take above images and push them to docker hub
    - docker push mhnm02/multi-client
    - docker push mhnm02/multi-nginx
    - docker push mhnm02/multi-server
    - docker push mhnm02/multi-worker
